// --- MAIN PAGE ---
var classicGame = document.querySelector('.classic-game');
var gamePanel = document.querySelector('.game-panel');
var classicIcons = document.querySelector('.classic-icons');
var difficultGame = document.querySelector('.difficult');
var chooseBattle = document.querySelector('.choose-battle');
var chooseFighter = document.querySelector('.choose-fighter');
var zombieRock = document.getElementById('zombie-rock')
var weapon = document.getElementById('weapon')
var paper = document.getElementById('paper')



// --- Event Listeners --
classicGame.addEventListener('click', chooseClassicGame)



// -- FUNCTIONS --
function chooseClassicGame() {
classicIcons.classList.remove('hidden');
classicGame.classList.add('hidden');
difficultGame.classList.add('hidden');
chooseFighter.classList.remove('hidden');
chooseBattle.classList.add('hidden');
}




// when user clicks their icon, their icon is displayed with a random icon
// that is generated by the computer
// human loses = "braaaaiiiinnnns" innerText



gamePanel.addEventListener('click', function(event) {
 if (event.target.classList.contains('fighter-icon') === true) {
classicIcons.innerHTML =
`<img class="fighter-icon" id="${event.target.id}" src="${event.target.src}">`
}
  });

// chooseGameView.addEventListener('click', function(event) {
//   humanPlayer.takeTurn(event)
// })







// GAME PAGE ----------
// tie = "safe for now!"

// shows human or zombie with win
// score counter
